# docker-compose.yml
services:
  rag-admin:
    build: .
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./nginx:/etc/nginx  # Add Nginx configuration volume
      - /etc/letsencrypt:/etc/letsencrypt  # SSL certificates volume
      - chroma_data:/app/data/chroma_db
      - chroma_index:/app/data/index
      - model_cache:/root/.cache  # Changed to parent cache directory
    environment:
      - VIRTUAL_HOST=ollama.easystreet.studio
      - LETSENCRYPT_HOST=ollama.easystreet.studio
      - CHROMA_DB_PATH=/app/data/chroma_db
      - CHROMA_DB_INDEX=/app/data/index
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
    networks:
      - rag-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - rag-admin
    networks:
      - rag-network

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "sh"
    command: >
      -c '
        chmod -R 755 /etc/letsencrypt &&
        certbot renew --force-renewal
      '
    user: root

volumes:
  chroma_data:
    driver: local
  chroma_index:
    driver: local
  model_cache:    
    driver: local

networks:
  rag-network:
    driver: bridge